FROM node:21.1.0-alpine3.18 as BUILD_IMAGE

WORKDIR /app

COPY package.json .

RUN npm install

COPY . .

ARG MY_APP_VITE_URL_INFO_DATA
ARG MY_APP_VITE_URL_MAP_DATA
ARG MY_APP_VITE_URL_MVT
ARG MY_APP_VITE_URL_GOOGLE_MAP_API_TERRAIN
ARG MY_APP_VITE_MAP_DEFAULT_CENTER
ARG MY_APP_VITE_MAP_DEFAULT_ZOOM

ENV VITE_URL_INFO_DATA=$MY_APP_VITE_URL_INFO_DATA
ENV VITE_URL_MAP_DATA=$MY_APP_VITE_URL_MAP_DATA
ENV VITE_URL_MVT=$MY_APP_VITE_URL_MVT
ENV VITE_URL_GOOGLE_MAP_API_TERRAIN=$MY_APP_VITE_URL_GOOGLE_MAP_API_TERRAIN
ENV VITE_MAP_DEFAULT_CENTER=$MY_APP_VITE_MAP_DEFAULT_CENTER
ENV VITE_MAP_DEFAULT_ZOOM=$MY_APP_VITE_MAP_DEFAULT_ZOOM

RUN npm run build

FROM nginx:1.21.6-alpine as PRODUCTION_IMAGE

COPY --from=BUILD_IMAGE /app/dist/ /usr/share/nginx/html

COPY env.sh /docker-entrypoint.d/env.sh

RUN chmod +x /docker-entrypoint.d/env.sh
    