FROM node:21.1.0-alpine3.18 as BUILD_IMAGE

WORKDIR /app

COPY package.json .

RUN npm install

COPY . .

ARG VITE_URL_INFO_DATA
ARG VITE_URL_MAP_DATA
ARG VITE_URL_MVT
ARG VITE_URL_GOOGLE_MAP_API_TERRAIN
ARG VITE_MAP_DEFAULT_CENTER
ARG VITE_MAP_DEFAULT_ZOOM

ENV VITE_URL_INFO_DATA=$VITE_URL_INFO_DATA
ENV VITE_URL_MAP_DATA=$VITE_URL_MAP_DATA
ENV VITE_URL_MVT=$VITE_URL_MVT
ENV VITE_URL_GOOGLE_MAP_API_TERRAIN=$VITE_URL_GOOGLE_MAP_API_TERRAIN
ENV VITE_MAP_DEFAULT_CENTER=$VITE_MAP_DEFAULT_CENTER
ENV VITE_MAP_DEFAULT_ZOOM=$VITE_MAP_DEFAULT_ZOOM

RUN npm run build

FROM nginx:1.21.6-alpine as PRODUCTION_IMAGE

COPY --from=BUILD_IMAGE /app/dist/ /usr/share/nginx/html

COPY env.sh /docker-entrypoint.d/env.sh

RUN chmod +x /docker-entrypoint.d/env.sh
    